---
#
# VARS_LIST : time_delay
#
- name: test Playbook
  hosts:
    - appserver
  gather_facts: True
  tasks:
    - name: Step 1
      command: sleep {{ time_delay }}
    - name: Step 2
      command: sleep {{ time_delay }}
      tags:
        - onlyme
